### ISSUE TITLE
Missing update...

### ISSUE THREAD

**Issue by graanco** [homebridge-simplisafe3/homebridge-simplisafe3#166]
I am not sure what is going but when I arm my house the icon just sits there spinning. This happened since last update. It looks like my system isn’t getting the final call to show that the alarm setting has changed.

**Comment by graanco** [comment]
![Uploading 79322715-FAB5-4500-B462-50420A0B7B04.png…]()

**Comment by graanco** [comment]
Okay wow thanks for the quick close. But the issue is still there. I tried sharing the image of the alarm just spinning

**Comment by shamoon** [comment]
The issue was closed because you didn't follow the template, as the bot politely explained =) Also you didn't finish uploading the image I think.

Theres nothing in the last few updates that would have caused changing alarm state to fail, at least not that Im aware of. If you can provide logs and all of the other info requested in the template 😉 I can take a look
