### ISSUE TITLE
Devices do not show up after disabling and enabling

### ISSUE THREAD

**Issue by TheTherminator** [homebridge-simplisafe3/homebridge-simplisafe3#244]
Hi,

I had to  troubleshoot something with my homebridge config and disabled simplysafe for that. After re-enabling the simplysafe devices did not show up again. Even after deinstallation and re-installation of the plug in, no change. There is also no single entry from simplysafe in my log. 

What am I doing wrong?

**Comment by shamoon** [comment]
Hi @TheTherminator sorry about the bot but I would need a little more info to be able to help. It sounds like you're not setting things up correctly so I'm not sure the issue is this plug-in itself. There are many guides on the web for how to setup homebridge.

It may help to enable the `debug` setting for this plug-in and extra logging for the entire homebridge install.
