### ISSUE TITLE
Wrong URL when signing in to SimpliSafe Website

### ISSUE THREAD

**Issue by enderboy987** [homebridge-simplisafe3/homebridge-simplisafe3#261]
### Describe The Bug:
A simple spelling error leading to the inability to use the link attached in the plugin's settings.

### To Reproduce:
Use the current link.

### Expected behavior:
I expected to be taken to SimpliSafe's website.

### Environment:

* **Plugin version**: homebridge-simplisafe3@1.8.4
* **Node.js Version**: v16.13.0
* **NPM Version**: v16.13.0
* **Homebridge Version**: 1.3.8
* **Operating System**: Raspbian

### Homebridge Config:
https://auth.simplisafe.com/authorize?client_id=42aBZ5lYrVW12jfOuu3CQROitwxg9sN5&scope=offline_access%20email%20openid%20https://api.simplisafe.com/scopes/user:platform&response_type=code&redirect_uri=com.simplisafe.mobile%3A%2F%2Fauth.simplisafe.com%2Fios%2Fcom.simplisafe.mobile%2Fcallback&code_challenge_method=S256&code_challenge=ZSeyNn55boCNrUDd-Kd8Vz1AnIMiJV9bZQwCjKKxh7I&audience=https://api.simplisafe.com/&auth0Client=eyJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsiaU9TIjoiMTUuMCIsInN3aWZ0IjoiNS54In0sInZlcnNpb24iOiIxLjMzLjAifQ 

I have so far noticed at least one issue with the spelling of the URL, notice on the section "code&redirect_uri". The section should read "code&redirect_url". I am looking through the URL to see if I can't spot any other spelling errors that would impede the SimpliSafe login process.

### Screenshots:
![image](https://user-images.githubusercontent.com/95107395/143659518-18cdaca2-f1b0-438c-b94f-182414def34c.png)

First image is the direct link from the Plugin.

![image](https://user-images.githubusercontent.com/95107395/143659559-30059d3c-adc3-4016-8cee-8308bdb4202c.png)

Second image is with the spelling issue noted corrected, still looking for any others.

### Logs:
No logs applicable.

**Comment by shamoon** [comment]
Hi @enderboy987 Sorry, no, you are not correct that there is a spelling error, `redirect_uri` is the correct parameter as noted in the auth0 documentation https://auth0.com/docs/authorization/protocols/protocol-oauth2#authorization-endpoint

After all, if that was the case no one would have been able to authenticate since this was released weeks ago...

Each link generated by the plugin only works one time, which is why you are getting the error in the second screenshot.

As for your issue in general, as noted in the documentation, when using browsers like Google Chrome, the URL that you need to copy & paste back into Homebridge doesnt load and instead you need to get it from the console, just like is shown in your first screenshot. Please read the documentation carefully https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#simplisafe-authentication
