### ISSUE TITLE
error when using with Homebridge and Simplisafe

### ISSUE THREAD

**Issue by chenchaso** [homebridge-simplisafe3/homebridge-simplisafe3#268]
### Describe The Bug:

I get an error in Homebridge ui
21 errors were received from the SimpliSafe API while refereshing sensors in the last 5 minutes. Enable debug logging for detailed output. It does not let me set away or home in HomeKit app. 

### To Reproduce:

I do not have to do anything it happens and pull sup every five minutes
### Expected behavior:

Stay connected with Homebridge and home kit to allow me to change alarm statuses in HomeKit
### Environment:

* **Plugin version**: 
* homebridge-simplisafe3 v1.8.8
* **Node.js Version**: 
* 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: 

```json
Paste the relevant section of your homebridge config.json here
```

### Screenshots:

![Screen Shot 2021-12-23 at 12 18 20 PM](https://user-images.githubusercontent.com/17443883/147273090-32dfb194-b723-4672-b72d-f040066ef3cc.png)

### Logs:

[Link to logs]()
```
Paste Homebridge Logs here
```

**Comment by shamoon** [comment]
Hey @chenchaso you need to restart after enabling debug so that it will show the errors. But a lot of those errors from the API are just the API not being reliable eg nothing to really worry about. But from the sound of it something may be up. Please post after restarting with debug enabled and include up through attempting to use the alarm in HomeKit.

thabks

Ps. Please post the actual text or even a link to text file rather than screenshots of the logs.

**Comment by chenchaso** [comment]
Thanks for that sorry I am new to this whole thing it seems like its working off and on  if it continues to be an issue I will try my best to do this correctly next time. Would I do it via the create an issue or in a forum? Thank you

**Comment by shamoon** [comment]
No problem at all.

Either one is fine but issues should generally be a bug, something you think is wrong with the plug-in that you can reproduce. If you think it’s just an issue you’re having discussion might make more sense. I can always convert one into the other after-the-fact anyway.
