### ISSUE TITLE
Disable ability to arm/disarm

### ISSUE THREAD

**Issue by cgmckeever** [homebridge-simplisafe3/homebridge-simplisafe3#270]
### Is your feature request related to a problem? Please describe:

I dont trust technology ;)

### Describe the solution you'd like:

It would be great to be able to disable turning off and/or arming for those that are fearful of device compromise. 
I wouldnt mind being able to ARM the system, and see current status. But being able to disable remote DISARM would be nice.

### Describe alternatives you've considered:
Removing the plugin, which would make me sad

**Comment by cgmckeever** [comment]
I searched old issues for this, and did not find a good match. Not sure if this already was asked

**Comment by cgmckeever** [comment]
Another option here would be the ability to remove the `Simplisafe 3` device from the sync. Ive tried to exclude the serial number shown in the Homebridge Settings, and it still appears in the Home App. That device also does not have a `REMOVE` setting in the Home App either

**Comment by cgmckeever** [comment]
This is probably complete hacky, and far from fully functional, but maybe it gives one of the maintainers a 💡 

Removing `Characteristic.SecuritySystemTargetState.DISARM` from `VALID_TARGET_STATE_VALUES` seems to at least suppress the ability to turn off via Apple Home - which is all I want

this.VALID_TARGET_STATE_VALUES = [
            Characteristic.SecuritySystemTargetState.STAY_ARM,
            Characteristic.SecuritySystemTargetState.AWAY_ARM,
            //Characteristic.SecuritySystemTargetState.DISARM
        ];

https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/blob/194f1fc3b95886c03a3c2807a134756d68a49060/src/accessories/alarm.js#L59

**Comment by cgmckeever** [comment]
thats works, but sucks . makes the switch in Apple Home all weird .. back to the drawing board

**Comment by shamoon** [comment]
Hey @cgmckeever yes I think the only way to do this that would make sense would to be able to exclude the alarm device similar to how you can with sensors. That would however require a significant amount of work because the plugin is written with the alarm centrally in mind. Frankly I think its a bit of an odd request since between Apple and SS I think SS is very much the weak link but of course using this plugin requires you have the SS plan already... Anyway, point is unless at least a few other users ask for this I am not currently planning to invest the time to implement it myself. Of course open to PRs from others...
