### ISSUE TITLE
SimpliSafe Wireless Outdoor Security Camera Support

### ISSUE THREAD

**Issue by unipheas** [homebridge-simplisafe3/homebridge-simplisafe3#277]
### Is your feature request related to a problem? Please describe:
Currently the SimpliSafe Wireless Outdoor Security Camera are not supported and do not display in Apple Home App

### Describe the solution you'd like:
It would be nice if these new cameras were supported.

### Describe alternatives you've considered:
no alternatives

### Additional context:
n/a

**Comment by shamoon** [comment]
Duplicate of #240 

Hi @unipheas Unfortunately I dont have one of those cameras to test with and they seem to use a different encoding / streaming structure than the previous cameras so I dont really have any way to work on this.

**Comment by shamoon** [comment]
Hey Brian, I appreciate the offer but a few things:

- I would likely need to have a permanent camera of my own for testing as needed. Since I dont really need one in my life (and frankly they havent gotten great reviews) its not something Im looking to purchase and dont feel comfortable accepting (for the same reasons this project doesnt accept donations). The best Ive been thinking is to find a beat-up one online somewhere for cheap. That opportunity hasn't presented itself, yet.
- Even if I can get my hands on one, I cant guarantee support. The older cameras took a lot of reverse-engineering and even so its still a bit less robust than I wish. SS dont use rtsp or anything like that.
- That said, Im not convinced that these cameras use a dramatically different setup than the old ones, I just havent identified what the issue is.  Im totally open to PRs and collaboration, for neatness sake will keep it in #240
