### ISSUE TITLE
Mobile Device URL Method Broke

### ISSUE THREAD

**Issue by meowcrunch2287** [homebridge-simplisafe3/homebridge-simplisafe3#322]
The mobile device method described in the installation and setup instructions required a mobile type url to be displayed along with a confirmation code. Tried via IOS devices and different browsers that include Firefox, Chrome, Safari. All URL redirects are now associated with 'https://tsv.prd.platform.simplisafe.com/v1'

Propose that we move away from the mobile site url code to crawl for code generation and entire token manually in the setup instructions to copy and paste into a form area in the Config UX section and or during the CLI utility authentication.

Currently Running oznu/homebridge:latest-data-1 - Have tried both CLI utility and also the Config UX options both responses to get that URL is not a valid URL both from the email redirect being opened on MAC os and an IOS device without the SimpliSafe App.
<img width="994" alt="Screen Shot 2022-03-11 at 12 51 43 PM" src="https://user-images.githubusercontent.com/58232863/157923424-7469d5d7-ab23-4dcb-9339-4bc18392ec95.png">
<img width="994" alt="Screen Shot 2022-03-11 at 12 53 37 PM" src="https://user-images.githubusercontent.com/58232863/157923425-6cfb705c-754f-449b-9e5c-13185aa0d3e2.png">

**Comment by shamoon** [comment]
Hi @meowcrunch2287 As [noted in the docs](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#simplisafe-authentication), you cant do this on an iOS device, the URL youre getting is not the final one but on iOS theres no way to get it.

And unfortunately there are a limited number of choices for which URLs to use, they have it setup to only allow certain URLs, either the mobile one "com.simplisafe.mobile..." or "webapp.simplisafe.com..." which wouldn't work because it would just take you there.

On macOS, depending on which browser (and apparently even which version of Safari) you may need to look in the console output for the URL.

**Comment by shamoon** [comment]
Hi @meowcrunch2287 , if you are interested please check out https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/releases/tag/v1.10.0-beta.1 

As its a beta, if you install make sure you backup everything first just in case!
