### ISSUE TITLE
simplisafe doorbell cam

### ISSUE THREAD

**Issue by Brian8731** [homebridge-simplisafe3/homebridge-simplisafe3#366]
### Description

simplisafe plugin installed on hoobs and when i go to apple home app the cameras only work for 10 seconds then says no response. if i close out and go back they are available again but only for 10sec.

### Expected behavior

camera to stay live on apple home app

### Steps to reproduce

1.open home app
2. click on camera preview

### Homebridge logs

```bash
{
    "platform": "homebridge-simplisafe3.SimpliSafe 3",
    "refreshToken": "v1.MaVJQxpCR2HpmZyVhCPRY2ly-tRdDUGAhdqIE6zeolOKYyhrIar29fHUfiIN8lTTjrKljj_qNISatHdAOsjzHQM",
    "sensorRefresh": 15,
    "cameras": true,
    "debug": true,
    "cameraOptions": {
        "enableHwaccelRpi": false
    }
}
```

### Homebridge config.json contents

```json
{
    "platform": "homebridge-simplisafe3.SimpliSafe 3",
    "refreshToken": "v1.MaVJQxpCR2HpmZyVhCPRY2ly-tRdDUGAhdqIE6zeolOKYyhrIar29fHUfiIN8lTTjrKljj_qNISatHdAOsjzHQM",
    "sensorRefresh": 15,
    "cameras": true,
    "debug": true,
    "cameraOptions": {
        "enableHwaccelRpi": false
    }
}
```

### Plugin version

1.10.10

### Homebridge version

hoobs 

### Node.js version

node v

### Host OS

Raspbian

**Comment by shamoon** [comment]
Hi, so first of all you didnt post your logs, just the config 2x. Also, note that though they claim otherwise this plugin is built for homebridge not HOOBs, so I dont know this for sure, but that may be an issue.

When you do post logs, please make sure `debug` is enabled, restart, and run them all the way through the stream cutting out.

There are not any known issues about this and the plugin has been fairly unchanged for many months now.
